version: 2.1

orbs:
  maven: circleci/maven@2.0.0
  heroku: circleci/heroku@2.0.0
  docker: circleci/docker@2.1.4
  snyk: snyk/snyk@1.5.0

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run: |
                echo "Install dependencies"
                mvn clean install

  test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run: |
                echo "Running tests"
                mvn test

  publish:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - setup_remote_docker # Enables Docker commands within CircleCI
      - run:
          name: Build Jar File
          command: mvn clean install
      - run:
          name: Build Docker Image
          command: docker build -t k3llyz/module-4-group-assignment:latest .
      - run:
          name: Push Docker Image to DockerHub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push k3llyz/module-4-group-assignment:latest

  deploy:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - setup_remote_docker
      - heroku/install
      - run:
          name: Push to Heroku Container
          command: |
            heroku container:login
            heroku stack:set container -a module-4-group-assignment
            heroku container:push web -a module-4-group-assignment
            heroku container:release web -a module-4-group-assignment

workflows:
  assignment_workflow:
    jobs:
      - build:
          filters:
            branches:
              ignore: []
            tags:
              only: /^v.*/
      - test:
          requires:
            - build
          filters:
            branches:
              ignore: []
            tags:
              only: /^v.*/
      - publish:
          requires:
            - test
          filters:
            branches:
              ignore: feature
            tags:
              only: /^v.*/
      - deploy:
          requires:
            - publish
          filters:
            tags:
              only: /^v.*/
